/**
 * Default Extraction Patterns
 * ~25 patterns covering functions, data structures, routes, and hooks
 * for JS/TS/Python/PHP/Go/Rust/Java.
 *
 * These live in code, NOT in config.json. Config only stores overrides/additions.
 * Merge happens at runtime via getApplicablePatterns() in parser.ts.
 */

import type { ExtractionPattern } from './types.js';

export const DEFAULT_PATTERNS: ExtractionPattern[] = [
  // ─── Functions ───────────────────────────────────────────────────────────────

  {
    id: 'fn-js-function',
    description: 'JS/TS function declaration',
    category: 'function',
    regex: '(?:export\\s+)?(?:async\\s+)?function\\s+(\\w+)\\s*\\(([^)]*)\\)(?:\\s*:\\s*(\\S+))?',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'fn-js-arrow',
    description: 'JS/TS arrow function (const name = (...) =>)',
    category: 'function',
    regex: '(?:export\\s+)?const\\s+(\\w+)\\s*=\\s*(?:async\\s+)?\\(([^)]*)\\)(?:\\s*:\\s*(\\S+))?\\s*=>',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'fn-js-method',
    description: 'JS/TS class method',
    category: 'function',
    regex: '^\\s*(?:public\\s+|private\\s+|protected\\s+)?(?:static\\s+)?(?:async\\s+)?(\\w+)\\s*\\(([^)]*)\\)(?:\\s*:\\s*(\\S+))?\\s*\\{',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx'],
    source: 'default',
    enabled: true,
    priority: 5,
  },
  {
    id: 'fn-python-def',
    description: 'Python function/method',
    category: 'function',
    regex: 'def\\s+(\\w+)\\s*\\(([^)]*)\\)(?:\\s*->\\s*(\\S+))?:',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.py'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'fn-php',
    description: 'PHP function/method',
    category: 'function',
    regex: '(?:public|private|protected)?\\s*function\\s+(\\w+)\\s*\\(([^)]*)\\)(?:\\s*:\\s*(\\S+))?',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.php'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'fn-go-func',
    description: 'Go function declaration',
    category: 'function',
    regex: 'func\\s+(?:\\([^)]*\\)\\s+)?(\\w+)\\s*\\(([^)]*)\\)(?:\\s*(?:\\(([^)]+)\\)|([\\w*]+)))?',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.go'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'fn-rust-fn',
    description: 'Rust function declaration',
    category: 'function',
    regex: '(?:pub\\s+)?(?:async\\s+)?fn\\s+(\\w+)\\s*(?:<[^>]*>)?\\s*\\(([^)]*)\\)(?:\\s*->\\s*([\\w<>:&\\[\\]]+))?',
    flags: '',
    captures: { name: 1, params: 2, returnType: 3 },
    fileExtensions: ['.rs'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'fn-java-method',
    description: 'Java method declaration',
    category: 'function',
    regex: '(?:public|private|protected)\\s+(?:static\\s+)?(?:final\\s+)?(?:synchronized\\s+)?(\\w+(?:<[^>]+>)?)\\s+(\\w+)\\s*\\(([^)]*)\\)',
    flags: '',
    captures: { name: 2, params: 3, returnType: 1 },
    fileExtensions: ['.java'],
    source: 'default',
    enabled: true,
    priority: 10,
  },

  // ─── Data Structures ─────────────────────────────────────────────────────────

  {
    id: 'ds-ts-interface',
    description: 'TypeScript interface',
    category: 'datastructure',
    regex: '(?:export\\s+)?interface\\s+(\\w+)(?:\\s+extends\\s+(\\w+))?',
    flags: '',
    captures: { name: 1, parentName: 2 },
    fileExtensions: ['.ts', '.tsx'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'ds-ts-type',
    description: 'TypeScript type alias',
    category: 'datastructure',
    regex: '(?:export\\s+)?type\\s+(\\w+)(?:<[^>]*>)?\\s*=',
    flags: '',
    captures: { name: 1 },
    fileExtensions: ['.ts', '.tsx'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'ds-ts-enum',
    description: 'TypeScript enum',
    category: 'datastructure',
    regex: '(?:export\\s+)?(?:const\\s+)?enum\\s+(\\w+)',
    flags: '',
    captures: { name: 1 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'ds-python-dataclass',
    description: 'Python dataclass',
    category: 'datastructure',
    regex: '@dataclass[\\s\\S]*?class\\s+(\\w+)(?:\\(([^)]*)\\))?:',
    flags: '',
    captures: { name: 1, parentName: 2 },
    fileExtensions: ['.py'],
    source: 'default',
    enabled: true,
    framework: 'dataclasses',
    priority: 15,
  },
  {
    id: 'ds-python-pydantic',
    description: 'Pydantic BaseModel',
    category: 'datastructure',
    regex: 'class\\s+(\\w+)\\s*\\(\\s*(?:BaseModel|BaseSettings)\\s*\\):',
    flags: '',
    captures: { name: 1 },
    fileExtensions: ['.py'],
    source: 'default',
    enabled: true,
    framework: 'pydantic',
    priority: 15,
  },
  {
    id: 'ds-go-struct',
    description: 'Go struct',
    category: 'datastructure',
    regex: 'type\\s+(\\w+)\\s+struct',
    flags: '',
    captures: { name: 1 },
    fileExtensions: ['.go'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'ds-rust-struct',
    description: 'Rust struct',
    category: 'datastructure',
    regex: '(?:pub\\s+)?struct\\s+(\\w+)(?:<[^>]*>)?',
    flags: '',
    captures: { name: 1 },
    fileExtensions: ['.rs'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'ds-rust-enum',
    description: 'Rust enum',
    category: 'datastructure',
    regex: '(?:pub\\s+)?enum\\s+(\\w+)(?:<[^>]*>)?',
    flags: '',
    captures: { name: 1 },
    fileExtensions: ['.rs'],
    source: 'default',
    enabled: true,
    priority: 10,
  },
  {
    id: 'ds-java-record',
    description: 'Java record',
    category: 'datastructure',
    regex: '(?:public\\s+)?record\\s+(\\w+)\\s*\\(([^)]*)\\)',
    flags: '',
    captures: { name: 1, params: 2 },
    fileExtensions: ['.java'],
    source: 'default',
    enabled: true,
    priority: 10,
  },

  // ─── Routes ──────────────────────────────────────────────────────────────────

  {
    id: 'rt-express',
    description: 'Express route (app/router.get/post/put/delete/patch)',
    category: 'route',
    regex: '(?:app|router)\\.(get|post|put|delete|patch)\\s*\\(\\s*[\'"`]([^\'"`]+)[\'"`]',
    flags: 'i',
    captures: { method: 1, path: 2, name: 2 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
    source: 'default',
    enabled: true,
    framework: 'express',
    priority: 10,
  },
  {
    id: 'rt-fastapi',
    description: 'FastAPI route decorator',
    category: 'route',
    regex: '@(?:app|router)\\.(get|post|put|delete|patch)\\s*\\(\\s*[\'"]([^\'"]+)[\'"]',
    flags: 'i',
    captures: { method: 1, path: 2, name: 2 },
    fileExtensions: ['.py'],
    source: 'default',
    enabled: true,
    framework: 'fastapi',
    priority: 10,
  },
  {
    id: 'rt-flask',
    description: 'Flask route decorator',
    category: 'route',
    regex: '@(?:app|bp|blueprint)\\.route\\s*\\(\\s*[\'"]([^\'"]+)[\'"](?:.*methods\\s*=\\s*\\[([^\\]]+)\\])?',
    flags: 'i',
    captures: { path: 1, method: 2, name: 1 },
    fileExtensions: ['.py'],
    source: 'default',
    enabled: true,
    framework: 'flask',
    priority: 10,
  },
  {
    id: 'rt-nestjs-controller',
    description: 'NestJS @Get/@Post/@Put/@Delete decorator',
    category: 'route',
    regex: '@(Get|Post|Put|Delete|Patch)\\s*\\(\\s*(?:[\'"]([^\'"]*)[\'"])?\\s*\\)',
    flags: '',
    captures: { method: 1, path: 2, name: 2 },
    fileExtensions: ['.ts'],
    source: 'default',
    enabled: true,
    framework: 'nestjs',
    priority: 15,
  },
  {
    id: 'rt-nextjs-api',
    description: 'Next.js API route handler export',
    category: 'route',
    regex: 'export\\s+(?:async\\s+)?function\\s+(GET|POST|PUT|DELETE|PATCH)\\s*\\(',
    flags: '',
    captures: { method: 1, name: 1 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx'],
    source: 'default',
    enabled: true,
    framework: 'nextjs',
    priority: 15,
  },
  {
    id: 'rt-gin',
    description: 'Gin (Go) route registration',
    category: 'route',
    regex: '(?:r|router|group|g)\\.(GET|POST|PUT|DELETE|PATCH)\\s*\\(\\s*"([^"]+)"',
    flags: '',
    captures: { method: 1, path: 2, name: 2 },
    fileExtensions: ['.go'],
    source: 'default',
    enabled: true,
    framework: 'gin',
    priority: 10,
  },

  // ─── Hooks ───────────────────────────────────────────────────────────────────

  {
    id: 'hk-react-custom',
    description: 'React custom hook (function starting with use)',
    category: 'hook',
    regex: '(?:export\\s+)?(?:const\\s+(use\\w+)\\s*=|function\\s+(use\\w+))\\s*(?:(?:async\\s+)?\\(([^)]*)\\)(?:\\s*:\\s*(\\S+))?\\s*=>|\\(([^)]*)\\)(?:\\s*:\\s*(\\S+))?)',
    flags: '',
    captures: { name: 1, params: 3, returnType: 4 },
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx'],
    source: 'default',
    enabled: true,
    framework: 'react',
    priority: 20,
  },
];
